### ISSUE TITLE
Binary Release

### ISSUE THREAD

**Issue by nhalstead** [acidvegas/elastop#10]
Upon revision release, can you include the build output for MacOS ARM and Intel?

Storing build output in git is an anti-pattern.

**Comment by pateljoel** [comment]
+1 @nhalstead

Highlighted this here, but to no avail.

https://github.com/acidvegas/elastop/issues/6

**Comment by acidvegas** [comment]
Will add on next release

**Comment by acidvegas** [comment]
Binary included in the latest release. Will start including the binary for all future releases.
