### ISSUE TITLE
Query Rate is Insane

### ISSUE THREAD

**Issue by yonesko** [acidvegas/elastop#11]
<img width="397" alt="image" src="https://github.com/user-attachments/assets/83b6e3cb-2c0d-4f4c-8332-dc1e7bae31cc">

I've read your code, and it seems wrong to calculate Query Rate as `totalQueryes` divided by top window opened duration

**Comment by acidvegas** [comment]
Let me know if the latest release I just pushed fixes this for you

**Comment by yonesko** [comment]
better, tkanks
