### ISSUE TITLE
Certificate authentication

### ISSUE THREAD

**Issue by stoeps13** [acidvegas/elastop#15]
We're using client certificates for authentication. User/password and api are disabled.

Do you have plans to support client certs?

Regards
Cheis

**Comment by acidvegas** [comment]
Will add this into the next commit

**Comment by acidvegas** [comment]
> We're using client certificates for authentication. User/password and api are disabled.
> 
> Do you have plans to support client certs?
> 
> Regards Cheis

Added this feature on [273fed1](https://github.com/acidvegas/elastop/commit/273fed17767fc1d662574ed17d47ed090b652470), let me know if it works for you & ill push a new release

**Comment by stoeps13** [comment]
Works great thanks!
