### ISSUE TITLE
Heap shows as GB when it's MB

### ISSUE THREAD

**Issue by neeej** [acidvegas/elastop#2]
The Heap says G, where it should be M
![image](https://github.com/user-attachments/assets/b07cd9f8-0846-4c97-8904-3bf240dd06db)

The percentage is correct though.

**Comment by acidvegas** [comment]
> The Heap says G, where it should be M ![image](https://private-user-images.githubusercontent.com/35762408/390991993-b07cd9f8-0846-4c97-8904-3bf240dd06db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjQ3NzYsIm5iZiI6MTczMjg2NDQ3NiwicGF0aCI6Ii8zNTc2MjQwOC8zOTA5OTE5OTMtYjA3Y2Q5ZjgtMDg0Ni00Yzk3LTg5MDQtM2JmMjQwZGQwNmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA3MTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NTRlOGY0NzNhZDhkYjdiZjY3NWNhZTQyZWMzYzQ4MDA4ZjhmZmM3ZjBhMjNmYTE2ODE3MzJkYTgzNzY2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s7kmfz7c7L6UNPFrCydRAbjAEbqAadU6Vk1kA6QSe-s)
> 
> The percentage is correct though.

does [744fd5a](https://github.com/acidvegas/elastop/commit/744fd5a57d78842b1ac3f2d8000d32ca3e20c0df) solve this for you?

**Comment by neeej** [comment]
Yes 👍
