### ISSUE TITLE
Disks shows as TB when it's GB

### ISSUE THREAD

**Issue by neeej** [acidvegas/elastop#3]
Disks are always shown as T for each host total disk size
![image](https://github.com/user-attachments/assets/ae64a997-9d1f-4cf5-9066-47bd28a918ce)

These disks are however in GB sizes

**Comment by acidvegas** [comment]
> Disks are always shown as T for each host total disk size ![image](https://private-user-images.githubusercontent.com/35762408/390993723-ae64a997-9d1f-4cf5-9066-47bd28a918ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjQ3NzYsIm5iZiI6MTczMjg2NDQ3NiwicGF0aCI6Ii8zNTc2MjQwOC8zOTA5OTM3MjMtYWU2NGE5OTctOWQxZi00Y2Y1LTkwNjYtNDdiZDI4YTkxOGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA3MTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YmFmNGRmMDQyMDdkMTRhYTc2MThiOGQ5YTYxNzE1ZmNhMDY5NzY1NTk0ZmQ1YmFhMTRiMjZmNWNlMmM5ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nlv5hzYZVcZfwApzXwZabq8XDnABq6suLw98EH-ewpM)
> 
> These disks are however in GB sizes

does [744fd5a](https://github.com/acidvegas/elastop/commit/744fd5a57d78842b1ac3f2d8000d32ca3e20c0df) solve this for you?

**Comment by neeej** [comment]
Yes 👍
