### ISSUE TITLE
Error at startup: panic: strings: negative Repeat count

### ISSUE THREAD

**Issue by poulfoged** [acidvegas/elastop#5]
Getting this error at startup

`panic: strings: negative Repeat count [recovered]
	panic: strings: negative Repeat count

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	/Users/modec/go/pkg/mod/github.com/rivo/tview@v0.0.0-20241103174730-c76f7879f592/application.go:297 +0x45
panic({0xcc0db20?, 0xcc85120?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
strings.Repeat({0xcbdf6b0?, 0x6?}, 0xc000515ba8?)
	/usr/local/go/src/strings/strings.go:569 +0x56b
main.main.func1()
	/Users/modec/Installed/elastop/elastop.go:698 +0xb74
main.main.func2.1()
	/Users/modec/Installed/elastop/elastop.go:1048 +0x13
main.main.func2.(*Application).QueueUpdateDraw.2()
	/Users/modec/go/pkg/mod/github.com/rivo/tview@v0.0.0-20241103174730-c76f7879f592/application.go:862 +0x22
github.com/rivo/tview.(*Application).Run(0xc0002300e0)
	/Users/modec/go/pkg/mod/github.com/rivo/tview@v0.0.0-20241103174730-c76f7879f592/application.go:485 +0xd55
main.main()
	/Users/modec/Installed/elastop/elastop.go:1080 +0xc94`

**Comment by acidvegas** [comment]
> Getting this error at startup
> 
> `panic: strings: negative Repeat count [recovered] panic: strings: negative Repeat count
> 
> goroutine 1 [running]: github.com/rivo/tview.(*Application).Run.func1() /Users/modec/go/pkg/mod/github.com/rivo/tview@v0.0.0-20241103174730-c76f7879f592/application.go:297 +0x45 panic({0xcc0db20?, 0xcc85120?}) /usr/local/go/src/runtime/panic.go:785 +0x132 strings.Repeat({0xcbdf6b0?, 0x6?}, 0xc000515ba8?) /usr/local/go/src/strings/strings.go:569 +0x56b main.main.func1() /Users/modec/Installed/elastop/elastop.go:698 +0xb74 main.main.func2.1() /Users/modec/Installed/elastop/elastop.go:1048 +0x13 main.main.func2.(*Application).QueueUpdateDraw.2() /Users/modec/go/pkg/mod/github.com/rivo/tview@v0.0.0-20241103174730-c76f7879f592/application.go:862 +0x22 github.com/rivo/tview.(*Application).Run(0xc0002300e0) /Users/modec/go/pkg/mod/github.com/rivo/tview@v0.0.0-20241103174730-c76f7879f592/application.go:485 +0xd55 main.main() /Users/modec/Installed/elastop/elastop.go:1080 +0xc94`

Does [e18be60](https://github.com/acidvegas/elastop/commit/e18be60221129d8d9fd941c44e6b44ff7b639913) solve this for you?

**Comment by poulfoged** [comment]
Yes, thank you!
