### ISSUE TITLE
Cannot install via Homebrew / Linuxbrew

### ISSUE THREAD

**Issue by pateljoel** [acidvegas/elastop#6]
I just came across this tool here on Github and it really looks awesome! However, I found it very difficult to install this on my computer and could not easily install it from Homebrew or even Linuxbrew.

Are you planning to make this available on Homebrew or have binaries available in the releases section? Would be great if I could just use brew to install this quickly.

Thank you for building this!

**Comment by acidvegas** [comment]
There is a binary in the repo already.

**Comment by pateljoel** [comment]
@acidvegas I mean here for prebuilt binary releases:

https://github.com/acidvegas/elastop/releases

It would be easier to download prebuilt binaries from there (or Homebrew) [releases page](https://github.com/acidvegas/elastop/releases) rather than cloning the repo with git or manually compiling it.

I have also downloaded the binary in the repo and found out that it isn't compatible with my system (i'm on macOS).

**Comment by acidvegas** [comment]
Binary included in the latest release. Will start including the binary for all future releases.
