### ISSUE TITLE
Support for HTTPS protocol

### ISSUE THREAD

**Issue by hintdesk** [acidvegas/elastop#7]
Hi,
I would like to connect to my instance but it's not possible because my Elasticsearch instance is available over HTTPS:443.
The tool is currently fixed by HTTP therefore I can't connect to the instance.

Can you please make HTTPS connection possible for the tool?

Thank you.
Regards.

**Comment by damjank12** [comment]
yeah, that is also form my side - almost no one is running ES in non-TLS mode... or if it is possible with this version, describe how to do it. Thank you!

**Comment by Sabrimjd** [comment]
Same here, we don't do ES without HTTPS anymore, it looks like it is hardcoded for HTTP https://github.com/acidvegas/elastop/blob/2bc93bf707b72412bba906c7ec951cc735213684/elastop.go#L561

**Comment by acidvegas** [comment]
Will fix this today. I run elasticsearch behind tailscale which is why it was http only, but its easy to implement https

**Comment by acidvegas** [comment]
Ok, just pushed an update to allow HTTPS support. You specify `http://` or `https://` in the `-host` argument. Let me know if this works for any of you guys @hintdesk @damjank12 @Sabrimjd

**Comment by damjank12** [comment]
Bravo! Works for me! Thank you for your prompt response!

**Comment by Sabrimjd** [comment]
Works for me 2 thanks a lot for this quick fix !

-------- Message d'origine --------
