### ISSUE TITLE
Is it possible to use api key to connect to the elasticsearch cluster?

### ISSUE THREAD

**Issue by srkntrn** [acidvegas/elastop#8]

**Comment by acidvegas** [comment]
Yes I will add API support on the next commit. Forgot I left it out when I was deving this

**Comment by acidvegas** [comment]
API support added in [55db2a7](https://github.com/acidvegas/elastop/commit/55db2a7a136a8331dacccac79a44e57f1586af53).

Please re-open this issue if you have any problems with using API authentication.

I will add it to the next release once I finish added some more features
